### ISSUE TITLE
Typo that gives error while building

### ISSUE THREAD

**Issue by PaulSimode** [aave/aave-v3-deploy#49]
There seems to be a typing error in [helpers/index.ts](https://github.com/aave/aave-v3-deploy/blob/main/helpers/index.ts), line 17.

I believe the correct path is `"../tasks/market-registry/market-registry_add"` instead of `"../tasks/market-registry/market-registry:add"`. Changing this allowed me to continue with building.

The corresponding pull request is #48.

**Comment by miguelmtzinf** [comment]
Fixed in https://github.com/aave/aave-v3-deploy/pull/51
